"use client";
import { useEffect, useState } from "react";
import type { analyticsReport } from "../../../lib/analytics-store";
import { kigaliDay } from "../../../lib/analytics-policy";
import styles from "./analytics.module.css";
type Report = Awaited<ReturnType<typeof analyticsReport>>;
const names: Record<string, string> = { page_view: "Page views", product_view: "Product views", whatsapp_click: "WhatsApp outbound clicks", rwanda_order_click: "Rwanda order CTA clicks", partnership_click: "Partnership CTA clicks", add_to_cart: "Add to cart", checkout_started: "Checkout started", order_requested: "Order requests saved", wholesale_started: "Wholesale form started", wholesale_handoff: "Wholesale WhatsApp handoffs", sample_handoff: "Sample WhatsApp handoffs", contact_handoff: "Contact WhatsApp handoffs", foundation_interaction: "Foundation link clicks", tv_outbound: "TV outbound clicks", engagement: "Engagement heartbeats" };
const number = (value: number) => value.toLocaleString();
export function AnalyticsDashboard() {
  const today = kigaliDay();
  const [from, setFrom] = useState(kigaliDay(new Date(Date.now()-6*86400000))), [to, setTo] = useState(today);
  const [query, setQuery] = useState({ from, to, refresh: 0 });
  const [report, setReport] = useState<Report | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [enabled, setEnabled] = useState(true);
  useEffect(() => {
    const abort = new AbortController(); setLoading(true); setError(""); setReport(null);
    fetch(`/api/admin/analytics?from=${query.from}&to=${query.to}`, { cache: "no-store", signal: abort.signal }).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error || "Analytics could not be loaded."); setEnabled(data.enabled); setReport(data.report || null); }).catch(e => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!abort.signal.aborted) setLoading(false); });
    return () => abort.abort();
  }, [query]);
  function selectRange(days: number) { const start = days === 0 ? today.slice(0,8)+"01" : kigaliDay(new Date(Date.now()-(days-1)*86400000)); setFrom(start); setTo(today); setQuery({ from:start, to:today, refresh:Date.now() }); }
  const count = (event: string) => Number(report?.events.find(row=>row.name===event)?.count || 0);
  const metrics = report ? [["Visitors today", report.overview.today], ["Visitors yesterday", report.overview.yesterday], ["Visitors this week", report.overview.week], ["Visitors this month", report.overview.month], ["Visits · retained 90 days", report.overview.totalVisits], ["Visitors · selected range", report.summary.visitors], ["Page views · selected range", report.summary.pageViews], ["WhatsApp clicks", count("whatsapp_click")], ["Add to cart", count("add_to_cart")], ["Order requests saved", count("order_requested")], ["Completed orders · database", report.orders.completed]] as const : [];
  const daily: { day: string; visitors: number; views: number }[] = [];
  if (report) for (let d = Date.parse(report.range.from); d <= Date.parse(report.range.to); d += 86400000) { const day = new Date(d).toISOString().slice(0,10); daily.push(report.daily.find(row=>row.day===day) || { day, visitors:0, views:0 }); }
  const max = Math.max(1, ...daily.map(d=>Math.max(d.visitors,d.views)));
  function breakdown(title: string, key: string) { const rows = report?.breakdowns[key] || []; return <section className={styles.panel} key={key}><h2>{title}</h2><p className={styles.note}>Visits · selected range</p>{rows.length ? <ul className={styles.ranks}>{rows.map(row=><li key={row.name}><span>{row.name}</span><strong>{number(row.count)}</strong><meter min={0} max={Math.max(1,report?.summary.visits || 0)} value={row.count} aria-label={`${row.name}: ${row.count} visits`} /></li>)}</ul> : <p>No data.</p>}</section>; }
  return <main className={styles.page}>
    <header className={styles.header}><div><a href="/admin">← BaBra administration</a><p className={styles.eyebrow}>PRIVATE · ADMIN ANALYTICS</p><h1>Website visitors</h1><p>Consenting browsers and their activity on babra.store.</p></div><button type="button" onClick={()=>setQuery({...query,refresh:Date.now()})} disabled={loading}>Refresh</button></header>
    <div className={styles.filters}><div className={styles.presets}>{[["Today",1],["Last 7 days",7],["Last 30 days",30],["This month",0]].map(([label,days])=><button type="button" key={label} onClick={()=>selectRange(Number(days))}>{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();setQuery({from,to,refresh:Date.now()});}}><label>From<input type="date" required value={from} max={today} onChange={e=>setFrom(e.target.value)} /></label><label>To<input type="date" required value={to} max={today} onChange={e=>setTo(e.target.value)} /></label><button>Apply range</button></form></div>
    <p className={styles.note}>Africa/Kigali (UTC+2) · Up to 31 days per report · 90-day retention. Visitors are random browser identifiers, not verified people. Consent choices and blocking cause undercounting.</p>
    {loading && <p role="status" className={styles.state}>Loading analytics…</p>}
    {error && <p role="alert" className={styles.state}>{error}</p>}
    {!loading && !error && !enabled && <section className={styles.state}><h2>Analytics is not enabled</h2><p>No analytics data collected yet. Complete the database migration and analytics configuration before enabling collection.</p></section>}
    {report && <>
      {report.summary.visits === 0 && <p role="status" className={styles.state}>No analytics data collected yet{report.overview.totalVisits > 0 ? " for this date range" : ""}.</p>}
      <section className={styles.metrics} aria-label="Overview">{metrics.map(([label,value])=><article key={label}><h2>{label}</h2><strong>{number(value)}</strong></article>)}</section>
      <div className={styles.highlights}><span>Top page <strong>{report.pages[0]?.name || "—"}</strong></span><span>Top country <strong>{report.breakdowns.country[0]?.name || "—"}</strong></span><span>Top source <strong>{report.breakdowns.source[0]?.name || "—"}</strong></span></div>
      <section className={styles.panel}><h2>Traffic over time</h2><p>Visitors and page views per day. Days without recorded events show zero.</p><div className={styles.chart}>
        <svg viewBox="0 0 900 240" role="img" aria-label="Daily visitor and page view bar chart; exact figures in the table below">
          {daily.map((d,i)=>{const width=860/Math.max(1,daily.length),x=30+i*width;return <g key={d.day}><title>{d.day}: {d.visitors} visitors, {d.views} page views</title><rect x={x} y={205-d.visitors/max*180} width={Math.max(2,width*.36)} height={d.visitors/max*180} fill="#d6ad57"/><rect x={x+width*.4} y={205-d.views/max*180} width={Math.max(2,width*.36)} height={d.views/max*180} fill="#52b9cf"/></g>;})}<line x1="20" y1="205" x2="890" y2="205" stroke="#677080"/><text x="20" y="232" fill="#eee" fontSize="14">{report.range.from}</text><text x="890" y="232" textAnchor="end" fill="#eee" fontSize="14">{report.range.to}</text>
        </svg></div><p><span className={styles.gold}>■ Visitors</span> &nbsp; <span className={styles.blue}>■ Page views</span></p>
        <details><summary>Daily figures</summary><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Visitors</th><th>Views</th></tr></thead><tbody>{daily.map(d=><tr key={d.day}><th>{d.day}</th><td>{d.visitors}</td><td>{d.views}</td></tr>)}</tbody></table></div></details>
      </section>
      <div className={styles.grid}><section className={styles.panel}><h2>Popular pages</h2><div className={styles.tableWrap}><table><thead><tr><th>Page</th><th>Views</th><th>Visitors</th></tr></thead><tbody>{report.pages.map(row=><tr key={row.name}><th>{row.name}</th><td>{number(row.views)}</td><td>{number(row.visitors)}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><h2>Business actions</h2><ul className={styles.ranks}>{report.events.filter(row=>!["page_view","engagement"].includes(row.name)).map(row=><li key={row.name}><span>{names[row.name] || row.name}</span><strong>{number(row.count)}</strong></li>)}</ul><p className={styles.note}>Browser-reported actions can be incomplete or spoofed. Form handoffs open WhatsApp; they do not confirm submission or a conversation.</p></section></div>
      <div className={styles.grid}>{breakdown("Traffic sources","source")}{breakdown("Campaigns","campaign")}{breakdown("Approximate country","country")}{breakdown("Devices","device")}{breakdown("Browsers","browser")}{breakdown("Operating systems","os")}</div>
      <div className={styles.grid}><section className={styles.panel}><h2>Shopping journey</h2><p>Visits containing these actions, cumulatively. This is not an ordered sales funnel.</p><ol className={styles.funnel}><li>Product view <strong>{report.funnel.product}</strong></li><li>Also added to cart <strong>{report.funnel.cart}</strong></li><li>Also started checkout <strong>{report.funnel.checkout}</strong></li><li>Also saved an order request <strong>{report.funnel.requested}</strong></li></ol><p>Request rate: <strong>{report.funnel.product ? `${(100*report.funnel.requested/report.funnel.product).toFixed(1)}%` : "—"}</strong></p><p className={styles.note}>Completed orders use the existing database status and completion date. They are not linked to browser identifiers, so visitor-to-sale conversion is unavailable. A saved request is not a completed order.</p></section>
      <section className={styles.panel}><h2>WhatsApp journey</h2><p>{number(report.summary.visits)} visits → {number(report.funnel.whatsapp)} visits with a WhatsApp click.</p><p>{number(count("whatsapp_click"))} total outbound WhatsApp clicks.</p><p className={styles.note}>The CTA and outbound click are the same action. Conversations and WhatsApp sales cannot be inferred.</p><h2>Engagement estimate</h2><p>{report.summary.engagementSeconds}s average measured active time per visit.</p><p className={styles.note}>Visible-page heartbeats while recently active; approximate and incomplete. New vs returning visitors and per-page duration are not reliably measured.</p></section></div>
      <section className={styles.panel}><h2>Recent activity · last 15 minutes</h2><p className={styles.note}>Aggregated groups of at least five visits. No individual visitor timeline or identity.</p>{report.recent.length ? <ul className={styles.ranks}>{report.recent.map((r,i)=><li key={i}><span>{r.country} · {r.page} · {r.device}</span><strong>{r.visits} visits</strong></li>)}</ul> : <p>No recent groups meet the privacy threshold.</p>}</section>
      <p className={styles.note}>Updated {new Date(report.generatedAt).toLocaleString("en-GB",{timeZone:"Africa/Kigali"})} Kigali time. No historical traffic is backfilled. Unknown geography and source are retained as unknown.</p>
    </>}
  </main>;
}
