"use client";
import { useEffect, useState } from "react";

type Account = { affiliate: { code: string; status: string; commissionRateBasisPoints: number }; balances: Record<string, { approvedMinor: number; consumedMinor: number; availableMinor: number }>; referrals: Array<{ id: string; status: string; attributedAt: string }>; commissions: Array<{ id: string; status: string; amountMinor: number; currency: string }>; withdrawals: Array<{ id: string; status: string; amountMinor: number; currency: string }> };

async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed"); return data as T; }
const money = (minor: number, currency: string) => `${(minor / 100).toLocaleString()} ${currency}`;

export function AffiliatePortal() {
  const [account, setAccount] = useState<Account | null>(null); const [needsApplication, setNeedsApplication] = useState(false); const [amount, setAmount] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { const data = await request<Account>("/api/affiliate/summary"); setAccount(data); setNeedsApplication(false); } catch { setNeedsApplication(true); } }
  useEffect(() => { void load(); }, []);
  async function apply() { try { await request("/api/affiliate/application", { method: "POST", body: "{}" }); setMessage("Application submitted for review."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Application failed"); } }
  async function withdraw() { try { await request("/api/affiliate/withdrawals", { method: "POST", body: JSON.stringify({ amountMinor: Number(amount), currency: "RWF", idempotencyKey: crypto.randomUUID() }) }); setMessage("Withdrawal request submitted."); setAmount(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Withdrawal failed"); } }
  return <main className="min-h-screen bg-[#100b08] px-5 py-12 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[.2em] text-[#d6ad57]">BaBra Affiliate</p><h1 className="mt-3 font-serif text-5xl">Affiliate workspace</h1>{message && <p className="mt-5 rounded-xl border border-[#d6ad57]/30 p-4">{message}</p>}{needsApplication ? <button className="mt-8 rounded-full bg-[#f1d58b] px-6 py-3 font-black text-black" onClick={apply}>Apply to become an affiliate</button> : account ? <div className="mt-8 grid gap-6"><section className="grid gap-4 md:grid-cols-3"><Card title="Status" value={account.affiliate.status}/><Card title="Affiliate code" value={account.affiliate.code}/><Card title="Commission rate" value={`${account.affiliate.commissionRateBasisPoints / 100}%`}/></section><section className="grid gap-4 md:grid-cols-3">{Object.entries(account.balances).map(([currency, balance]) => <Card key={currency} title={`Available ${currency}`} value={money(balance.availableMinor, currency)}/>)}</section><section className="rounded-2xl border border-white/10 p-6"><h2 className="font-serif text-3xl">Request withdrawal</h2><div className="mt-4 flex flex-wrap gap-3"><input className="rounded-xl bg-black/30 px-4 py-3" type="number" min="1" placeholder="Amount in minor units" value={amount} onChange={(e)=>setAmount(e.target.value)}/><button disabled={account.affiliate.status!=="ACTIVE" || !amount} className="rounded-full bg-[#f1d58b] px-5 py-3 font-black text-black disabled:opacity-40" onClick={withdraw}>Submit request</button></div></section><section className="grid gap-4 md:grid-cols-3"><Card title="Referrals" value={String(account.referrals.length)}/><Card title="Commissions" value={String(account.commissions.length)}/><Card title="Withdrawals" value={String(account.withdrawals.length)}/></section></div> : <p className="mt-8">Loading secure affiliate account…</p>}</div></main>;
}
function Card({title,value}:{title:string;value:string}) { return <article className="rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-sm font-black uppercase tracking-wider text-[#d6ad57]">{title}</p><strong className="mt-3 block break-all text-2xl">{value}</strong></article>; }
