"use client";
import { useEffect, useState } from "react";

type Affiliate = {
  id:string; code:string; status:string; commissionRateBasisPoints:number;
  user:{fullName:string;email:string|null;phone:string|null};
  referrals:Array<{id:string;orderId:string;status:string;commission:{id:string}|null}>;
  commissions:Array<{id:string;referralId:string;status:string;amountMinor:number;currency:string}>;
  withdrawals:Array<{id:string;status:string;amountMinor:number;currency:string}>;
};
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data as T;}

export function AffiliateAdmin(){
  const [items,setItems]=useState<Affiliate[]>([]); const [rates,setRates]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
  async function load(){const data=await request<{affiliates:Affiliate[]}>("/api/admin/affiliates");setItems(data.affiliates);}
  useEffect(()=>{void load().catch(error=>setMessage(error.message));},[]);
  async function run(key:string,operation:()=>Promise<unknown>){if(busy)return;try{setBusy(key);setMessage("");await operation();await load();}catch(error){setMessage(error instanceof Error?error.message:"Operation failed");}finally{setBusy("");}}
  async function review(affiliate:Affiliate,status:"ACTIVE"|"REJECTED"|"SUSPENDED"){await run(`affiliate-${affiliate.id}`,()=>request("/api/admin/affiliates",{method:"PATCH",body:JSON.stringify({affiliateId:affiliate.id,status,commissionRateBasisPoints:status==="ACTIVE"?Number(rates[affiliate.id]||affiliate.commissionRateBasisPoints):undefined,reason:`Admin ${status.toLowerCase()} review`})}));}
  async function createCommission(referralId:string){await run(`referral-${referralId}`,()=>request("/api/admin/affiliate-commissions",{method:"POST",body:JSON.stringify({referralId,includeDelivery:false})}));}
  async function transitionCommission(affiliate:Affiliate,id:string,status:"APPROVED"|"VOIDED"|"PAID"){const reason=status==="PAID"?window.prompt("Non-secret direct settlement reference")?.trim()||undefined:status==="VOIDED"?"Administrative review":undefined;if(status==="PAID"&&!reason)return;await run(`commission-${id}`,()=>request("/api/admin/affiliate-commissions",{method:"PATCH",body:JSON.stringify({affiliateId:affiliate.id,commissionId:id,status,reason})}));}
  async function transitionWithdrawal(affiliate:Affiliate,id:string,status:"APPROVED"|"REJECTED"|"PAID"){const payoutReference=status==="PAID"?window.prompt("Non-secret payout reference")?.trim()||undefined:undefined;if(status==="PAID"&&!payoutReference)return;await run(`withdrawal-${id}`,()=>request("/api/admin/affiliate-withdrawals",{method:"PATCH",body:JSON.stringify({affiliateId:affiliate.id,withdrawalId:id,status,payoutReference,adminReason:`Administrative ${status.toLowerCase()} review`})}));}
  return <main className="min-h-screen bg-[#100b08] px-5 py-12 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.2em] text-[#d6ad57]">Restricted administration</p><h1 className="mt-3 font-serif text-5xl">Affiliate operations</h1>{message&&<p className="mt-4 rounded-xl border border-red-300/30 p-4">{message}</p>}<div className="mt-8 grid gap-5">{items.map(affiliate=><article key={affiliate.id} className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-serif text-3xl">{affiliate.user.fullName}</h2><p className="text-white/60">{affiliate.code} · {affiliate.status}</p></div><div className="flex flex-wrap gap-2"><input aria-label="Commission basis points" className="w-40 rounded-xl bg-black/30 px-3" type="number" min="1" max="10000" value={rates[affiliate.id]??affiliate.commissionRateBasisPoints} onChange={event=>setRates({...rates,[affiliate.id]:event.target.value})}/><button disabled={Boolean(busy)} className="rounded-full bg-[#f1d58b] px-4 py-2 font-black text-black disabled:opacity-40" onClick={()=>void review(affiliate,"ACTIVE")}>Activate</button><button disabled={Boolean(busy)} className="rounded-full border border-white/20 px-4 py-2 disabled:opacity-40" onClick={()=>void review(affiliate,affiliate.status==="ACTIVE"?"SUSPENDED":"REJECTED")}>{affiliate.status==="ACTIVE"?"Suspend":"Reject"}</button></div></div><div className="mt-6 grid gap-6 lg:grid-cols-3">
    <section><h3 className="font-bold text-[#d6ad57]">Referrals</h3>{affiliate.referrals.map(referral=><div key={referral.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><span>{referral.orderId} · {referral.status}</span>{!referral.commission&&<button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void createCommission(referral.id)}>Create commission</button>}</div>)}</section>
    <section><h3 className="font-bold text-[#d6ad57]">Commissions</h3>{affiliate.commissions.map(commission=><div key={commission.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><span>{commission.amountMinor} {commission.currency} · {commission.status}</span>{commission.status==="PENDING"&&<><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionCommission(affiliate,commission.id,"APPROVED")}>Approve</button><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionCommission(affiliate,commission.id,"VOIDED")}>Void</button></>}{commission.status==="APPROVED"&&<><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionCommission(affiliate,commission.id,"PAID")}>Mark directly paid</button><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionCommission(affiliate,commission.id,"VOIDED")}>Void</button></>}</div>)}</section>
    <section><h3 className="font-bold text-[#d6ad57]">Withdrawals</h3>{affiliate.withdrawals.map(withdrawal=><div key={withdrawal.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><span>{withdrawal.amountMinor} {withdrawal.currency} · {withdrawal.status}</span>{withdrawal.status==="PENDING"&&<><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionWithdrawal(affiliate,withdrawal.id,"APPROVED")}>Approve</button><button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionWithdrawal(affiliate,withdrawal.id,"REJECTED")}>Reject</button></>}{withdrawal.status==="APPROVED"&&<button disabled={Boolean(busy)} className="underline disabled:opacity-40" onClick={()=>void transitionWithdrawal(affiliate,withdrawal.id,"PAID")}>Mark paid</button>}</div>)}</section>
  </div></article>)}</div></div></main>;
}
